rl_algo:
  cnn_cfg:
    name: CNN
    act: elu
    norm: none
    cnn_depth: 48
    cnn_kernels: [4, 4, 4, 4]
    spectral_normalisation: false

  policy:
    slot_extractor:
      name: ${rl_algo.cnn_cfg.name}
      act: ${rl_algo.cnn_cfg.act}
      norm: ${rl_algo.cnn_cfg.norm}
      cnn_depth: ${rl_algo.cnn_cfg.cnn_depth}
      cnn_kernels: ${rl_algo.cnn_cfg.cnn_kernels}
      spectral_normalisation: ${rl_algo.cnn_cfg.spectral_normalisation}
    slot_pooler:
      name: fetcher

  critics:
    slot_extractor:
      name: ${rl_algo.cnn_cfg.name}
      act: ${rl_algo.cnn_cfg.act}
      norm: ${rl_algo.cnn_cfg.norm}
      cnn_depth: ${rl_algo.cnn_cfg.cnn_depth}
      cnn_kernels: ${rl_algo.cnn_cfg.cnn_kernels}
      spectral_normalisation: ${rl_algo.cnn_cfg.spectral_normalisation}
    slot_pooler:
      name: fetcher
  
  value:
    slot_extractor:
      name: ${rl_algo.cnn_cfg.name}
      act: ${rl_algo.cnn_cfg.act}
      norm: ${rl_algo.cnn_cfg.norm}
      cnn_depth: ${rl_algo.cnn_cfg.cnn_depth}
      cnn_kernels: ${rl_algo.cnn_cfg.cnn_kernels}
      spectral_normalisation: ${rl_algo.cnn_cfg.spectral_normalisation}
    slot_pooler:
      name: fetcher

skill:
  trajectory_encoder:
    slot_extractor:
      name: ${rl_algo.cnn_cfg.name}
      act: ${rl_algo.cnn_cfg.act}
      norm: ${rl_algo.cnn_cfg.norm}
      cnn_depth: ${rl_algo.cnn_cfg.cnn_depth}
      cnn_kernels: ${rl_algo.cnn_cfg.cnn_kernels}
      spectral_normalisation: ${rl_algo.cnn_cfg.spectral_normalisation}
    slot_pooler:
      name: fetcher