rl_algo:
  policy:
    slot_extractor:
      name: dummy
    slot_pooler:
      name: fetcher

  critics:
    slot_extractor:
      name: dummy
    slot_pooler:
      name: fetcher
  
  value:
    slot_extractor:
      name: dummy
    slot_pooler:
      name: fetcher

skill:
  trajectory_encoder:
    slot_extractor:
      name: dummy
    slot_pooler:
      name: fetcher