defaults:
  - slate

tau_start: 0.1
tau_final: 0.1
tau_steps: 1

optimizer:
  encoder_optimizer:
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1

  slot_optimizer:
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1
  
  decoder_optimizer:
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1

  dvae_optimizer:
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1