defaults:
  - slot-attention

optimizer:
  encoder_optimizer:
    betas: [0.9, 0.9975]
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1

  slot_optimizer:
    betas: [0.9, 0.9975]
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1
  
  decoder_optimizer:
    betas: [0.9, 0.9975]
    lr_scheduler:
      warmup_steps: 0
      decay_steps: 1
      decay_rate: 1