globals:
  seed: 42

env:
  name: "decoupled_gripper"
  normalizer_type: "off"
  env_kwargs: 
    object_qty: 1
    object_names: ['box']

trainer_args:
  traj_batch_size: 8
  trans_optimization_epochs: 50

replay_buffer:
  max_transitions: 1000000

skill:
  name: "metra"
  discrete: false
  dim_option: 2