globals:
  encoder: 'cnn'

env:
  name: "dmc_quadruped"
  normalizer_type: "squashed"
  frame_stack: 3
  env_kwargs: null

trainer_args:
  trans_optimization_epochs: 225
  skill_optimization_epochs: 150
  policy_optimization_mult: 4

replay_buffer:
  skill:
    min_transitions: null
    max_transitions: 19_200
    batch_size: 256
  common:
    max_transitions: 300000

skill:
  name: "metra"
  discrete: false
  dim_option: 4