globals:
  seed: 46
  encoder: 'cnn'

env:
  name: "pixel_gripper"
  normalizer_type: "squashed"
  frame_stack: 3
  env_kwargs: 
    object_qty: 1
    object_names: ['box']
    obs_type: 'pixels'

trainer_args:
  trans_optimization_epochs: 200

replay_buffer:
  common:
    max_transitions: 300000

skill:
  name: "metra"
  discrete: false
  dim_option: 4