defaults:
  - _base
  - _self_
  - ocr: ???
  - dataset: ???
  - comet: train_ocr

num_workers: 4
prefetch_factor: 1
max_steps: 305_000
timesteps_for_checkpoint: [300_000]
save_name: ???

hydra:
  run:
    dir: ./outputs/train_ocr/${ocr.name}-${dataset.name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
